### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by fubhy** [recharts/recharts-scale#20]
Hi,

Currently, recharts-scale and thus recharts itself is not compatible with snowpack or any other esm based tooling / bundlers as the latest version on npm doesn't have a `module` build. I can see, that this was already submitted as a pull request and merged ~4 months ago. Would you mind tagging a new version (0.4.4) with this included?

Thanks!

**Comment by fubhy** [comment]
Ping @arcthur :-)

**Comment by avindra** [comment]
cc @xile611  can you look at this and #22 ?

**Comment by fubhy** [comment]
We have deployed a fork of this (as version `0.4.4`) on our public gemfury registry in case anyone needs an alternative while this remains unpublished on the official npm package: 

`yarn add recharts-scale --registry https://npm-proxy.fury.io/enzymefinance`

Feel free to use this until then.

**Comment by fubhy** [comment]
And with that I'm trying another friendly ping via @xile611 and @arcthur ;-)

**Comment by arcthur** [comment]
OK，I'm published. thanks

**Comment by fubhy** [comment]
Thanks @arcthur !
