### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by pakatagoh** [recharts/recharts-scale#24]
hi rechart-scale team,

![B52F482B-584F-434F-9DA4-708100458D1F](https://user-images.githubusercontent.com/37908805/111732353-36350c80-88b0-11eb-9b23-d7424aad4949.jpeg)

Something went wrong during my build process.   the error occured during yarn install. from I can see, the path to a file is incorrect from node_modules. 

Currently using recharts v^2.0.8

I'm not sure if it's due to the recent package update, but this failure just happened last night.

**Comment by pakatagoh** [comment]
Closing because it suddenly works. I believe it was some kind of cache issue

**Comment by pakatagoh** [comment]
![image](https://user-images.githubusercontent.com/37908805/111744915-e746a180-88c6-11eb-8663-60546e6ffb87.png)

Sorry it is still happening

**Comment by jmfrancois** [comment]
Yes I have this error during yarn upgrade command on my project.

If you look here and here 
https://unpkg.com/browse/recharts-scale@0.4.3/umd/
https://unpkg.com/browse/recharts-scale@0.4.4/umd/

The change is clear a js file name becomes a folder and it seems our OS do not like that.

**Comment by pakatagoh** [comment]
For anyone looking for a temporary workaround, here's mine

use `resolutions` in package.json

I'm using yarn and the `resolution` key forces recharts-scale to be version 0.4.2
```
"resolutions": {
    "**/recharts-scale": "0.4.2"
  },
```

if you're using npm, you'll need https://github.com/rogeriochaves/npm-force-resolutions to help achieve the same effect as yarn.

Hope this helps temporarily. And looking forward to a fix!

**Comment by jmfrancois** [comment]
please @arcthur ☝️   could you consider this issue ?

**Comment by jmfrancois** [comment]
I have spotted the commit: https://github.com/recharts/recharts-scale/commit/2d67af411ef048e8b5536123107fed3182969120#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L24

**Comment by strimbob** [comment]
could you merge the change from the pull?

**Comment by pakatagoh** [comment]
thanks for the PR @jmfrancois! hopefully it gets merged soon

**Comment by jmfrancois** [comment]
Thanks for the merge @arcthur. We just need a release to close this issue :)

**Comment by jmfrancois** [comment]
Maybe @xile611 you can create the release please ?

**Comment by arcthur** [comment]
released 0.4.5 @jmfrancois
