### ISSUE TITLE
Question: difference from d3-scale

### ISSUE THREAD

**Issue by okonet** [recharts/recharts-scale#5]
Can't https://github.com/d3/d3-scale/#continuous_ticks be used instead? Or what's the purpose of this library?

**Comment by xile611** [comment]
The function `ticks` of a scale in d3-scale just *Returns approximately count representative values from the scale’s domain*.

Here is a [simple example](https://jsfiddle.net/3r0d5zwq)：

```js
  var scale = d3_scale.scaleLinear().domain([10, 100]);
  scale.ticks(4);    // result: [20, 40, 60, 80, 100]
  scale.ticks(5);    // result: [20, 40, 60, 80, 100]
  scale.ticks(6);    // result: [20, 40, 60, 80, 100]
```

Then `recharts-scale` works differently, let's look at the [same example](https://jsfiddle.net/kmoyehhL/):

```js
var getNiceTickValues = RechartsScale.getNiceTickValues;
getNiceTickValues([10, 100], 4);  // result: [0, 35, 70, 105]
getNiceTickValues([10, 100], 5);  // result: [0, 25, 50, 75, 100]
getNiceTickValues([10, 100], 6);  // result: [0, 20, 40, 60, 80, 100]
```

**Comment by okonet** [comment]
Thanks! This makes sense.
