### ISSUE TITLE
isFinite not supported in IE11

### ISSUE THREAD

**Issue by larsthorup** [recharts/recharts-scale#8]
The use of Number.isFinite is not supported by IE11, failing with the error `Object doesn't support property or method 'isFinite'`

The source of the error appears to be this line:
https://github.com/recharts/recharts-scale/blob/1513ce2749320a0800f27682a2d48340f29be445/src/getNiceTickValues.js#L111

Using recharts-scale@0.4 from recharts@1.3.1

**Comment by avindra** [comment]
This is not generally a concern for the library author. If you need to cover your IE11 users, then your build system should be configured to add what is missing.

For `create-react-app`, see: https://create-react-app.dev/docs/supported-browsers-features/#supported-browsers

**Comment by vydimitrov** [comment]
It is concern as long as it says that it supports IE11, which was the case 2 years ago.

**Comment by avindra** [comment]
Actually, after reading `create-react-app` more closely, IE11 is explicitly **not** supported there:

> By default, the generated project supports all modern browsers. Support for Internet Explorer 9, 10, and 11 requires polyfills

This is in-line with what I would expect: that applications need to manage their polyfills/runtimes, not the library author.
